config/routes.rb
Rails.application.routes.draw do
  resources :news_articles
  resources :insights
  post '/paginate_insights' => 'insights#paginate_insights'
  post '/paginate_news_articles' => 'news_articles#paginate_news_articles'
  get 'home/article_html' => 'home#article_html'
  get 'home/insights_scrap' => 'home#insights_scrap'
  root 'home#index'

end

app/models/insight.rb
class Insight < ActiveRecord::Base
end

app/models/news_article.rb
class NewsArticle < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/home_controller.rb
class HomeController < ApplicationController


  def index
    
  end

  def article_html
    agent = Mechanize.new
    page = agent.get("https://letstalkpayments.com/fundchain-unveils-first-insight-of-blockchain-proof-of-concept-for-the-investments-funds-industry-the-smart-ta/")
    @page_html = page.search('.article-content').to_html

    render html: @page_html
# 
    # render_to_string(@page_html)
  end


  def insights_scrap
    # @article = Article.new
    # insights_articles = []
    i = 0
    agent = Mechanize.new
    url = 'https://letstalkpayments.com/tag/insights/'
    page = agent.get(url)

    next_page = page.link_with(text: 'Next Page ').href
    first_page = true

    while next_page.present?
      puts "#{i+=1}"
      unless first_page
        # break if i == 2
        break if page.link_with(text: 'Next Page ').blank?
        page = page.link_with(text: 'Next Page ').click
      end
      article_list = page.search('.article-list .item-content')

      article_list.each do |article|
        article_url  = article.at('h3 a')['href']
        article_page = agent.get(article_url)
        article_text = article_page.search('div .article-content p').to_html
        # article_page.search('div .article-content p').text.gsub(/\n\r\n\t\t\t.*\n.*/, '')
        
        article_text = article_text.slice(0..article_text.index(/<a style="display:block;" href="http:\/\/medici.letstalkpayments.com\/">/)).gsub(/\n\r\n\t\t.*/, '') rescue ''
        next if article_text.blank?
        title = article.at('.entry-title').text
        posted_at = article.at('h4').text.gsub!(/&nbsp.*/, '')
        posted_by = article.at('h4').text.gsub!(/.*&nbspBy\s\:/, '')

        Insight.find_or_create_by(title: title, posted_at: posted_at, posted_by: posted_by,  article_text: article_text)
      end
      first_page = false
    end
  end


  def news_scrap
    # @article = Article.new
    # insights_articles = []
    i = 0
    agent = Mechanize.new
    url = 'https://letstalkpayments.com/tag/news/'
    page = agent.get(url)

    next_page = page.link_with(text: 'Next Page ').href
    first_page = true

    while next_page.present?
      puts "#{i+=1}"
      unless first_page
        # break if i == 8
        break if page.link_with(text: 'Next Page ').blank?
        page = page.link_with(text: 'Next Page ').click
      end
      article_list = page.search('.article-list .item-content')

      article_list.each do |article|
        article_url  = article.at('h3 a')['href']
        article_page = agent.get(article_url)
        article_text = article_page.search('div .article-content p').to_html
        # article_page.search('div .article-content p').text.gsub(/\n\r\n\t\t\t.*\n.*/, '')
        
        article_text = article_text.slice(0..article_text.index(/<a style="display:block;" href="http:\/\/medici.letstalkpayments.com\/">/)).gsub(/\n\r\n\t\t.*/, '') rescue ''
        next if article_text.blank?
        title = article.at('.entry-title').text 
        posted_at = article.at('h4').text.gsub!(/&nbsp.*/, '')
        posted_by = article.at('h4').text.gsub!(/.*&nbspBy\s\:/, '')

        NewsArticle.find_or_create_by(title: title, posted_at: posted_at, posted_by: posted_by,  article_text: article_text)
      end
      first_page = false
    end
  end
end

app/controllers/insights_controller.rb
class InsightsController < ApplicationController
  before_action :set_insight, only: [:show, :edit, :update, :destroy]

  # GET /insights
  # GET /insights.json
  def index
    @insights = Insight.all
  end

  def paginate_insights
    @insights = Insight.page(params[:page].to_i).per(20)
    render json: @insights
  end

  # GET /insights/1
  # GET /insights/1.json
  def show
  end

  # GET /insights/new
  def new
    @insight = Insight.new
  end

  # GET /insights/1/edit
  def edit
  end

  # POST /insights
  # POST /insights.json
  def create
    @insight = Insight.new(insight_params)

    respond_to do |format|
      if @insight.save
        format.html { redirect_to @insight, notice: 'Insight was successfully created.' }
        format.json { render :show, status: :created, location: @insight }
      else
        format.html { render :new }
        format.json { render json: @insight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /insights/1
  # PATCH/PUT /insights/1.json
  def update
    respond_to do |format|
      if @insight.update(insight_params)
        format.html { redirect_to @insight, notice: 'Insight was successfully updated.' }
        format.json { render :show, status: :ok, location: @insight }
      else
        format.html { render :edit }
        format.json { render json: @insight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /insights/1
  # DELETE /insights/1.json
  def destroy
    @insight.destroy
    respond_to do |format|
      format.html { redirect_to insights_url, notice: 'Insight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_insight
      @insight = Insight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def insight_params
      params.require(:insight).permit(:title, :posted_at, :posted_by, :article_text)
    end
end

app/controllers/news_articles_controller.rb
class NewsArticlesController < ApplicationController
  before_action :set_news_article, only: [:show, :edit, :update, :destroy]

  # GET /news_articles
  # GET /news_articles.json
  def index
    @news_articles = NewsArticle.all
  end

  def paginate_news_articles
    @news_articles = NewsArticle.page(params[:page]).per(20)
    render json: @news_articles
  end

  # GET /news_articles/1
  # GET /news_articles/1.json
  def show
  end

  # GET /news_articles/new
  def new
    @news_article = NewsArticle.new
  end

  # GET /news_articles/1/edit
  def edit
  end

  # POST /news_articles
  # POST /news_articles.json
  def create
    @news_article = NewsArticle.new(news_article_params)

    respond_to do |format|
      if @news_article.save
        format.html { redirect_to @news_article, notice: 'News article was successfully created.' }
        format.json { render :show, status: :created, location: @news_article }
      else
        format.html { render :new }
        format.json { render json: @news_article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news_articles/1
  # PATCH/PUT /news_articles/1.json
  def update
    respond_to do |format|
      if @news_article.update(news_article_params)
        format.html { redirect_to @news_article, notice: 'News article was successfully updated.' }
        format.json { render :show, status: :ok, location: @news_article }
      else
        format.html { render :edit }
        format.json { render json: @news_article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news_articles/1
  # DELETE /news_articles/1.json
  def destroy
    @news_article.destroy
    respond_to do |format|
      format.html { redirect_to news_articles_url, notice: 'News article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news_article
      @news_article = NewsArticle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_article_params
      params.require(:news_article).permit(:title, :posted_at, :posted_by, :article_text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/insights_helper.rb
module InsightsHelper
end

app/helpers/news_articles_helper.rb
module NewsArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :posted_at %><br>
    <%= f.text_field :posted_at %>
  </div>
  <div class="field">
    <%= f.label :posted_by %><br>
    <%= f.text_field :posted_by %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/home/article_html.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-12">
			<%= @page_html %>
		</div>
	</div>
</div>

app/views/home/index.html.erb
HI, This Is LTP API APP.

app/views/insights/_form.html.erb
<%= form_for(@insight) do |f| %>
  <% if @insight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@insight.errors.count, "error") %> prohibited this insight from being saved:</h2>

      <ul>
      <% @insight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :posted_at %><br>
    <%= f.text_field :posted_at %>
  </div>
  <div class="field">
    <%= f.label :posted_by %><br>
    <%= f.text_field :posted_by %>
  </div>
  <div class="field">
    <%= f.label :article_text %><br>
    <%= f.text_area :article_text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/insights/edit.html.erb
<h1>Editing Insight</h1>

<%= render 'form' %>

<%= link_to 'Show', @insight %> |
<%= link_to 'Back', insights_path %>

app/views/insights/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Insights</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Posted at</th>
      <th>Posted by</th>
      <th>Article text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @insights.each do |insight| %>
      <tr>
        <td><%= insight.title %></td>
        <td><%= insight.posted_at %></td>
        <td><%= insight.posted_by %></td>
        <td><%= insight.article_text %></td>
        <td><%= link_to 'Show', insight %></td>
        <td><%= link_to 'Edit', edit_insight_path(insight) %></td>
        <td><%= link_to 'Destroy', insight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Insight', new_insight_path %>

app/views/insights/new.html.erb
<h1>New Insight</h1>

<%= render 'form' %>

<%= link_to 'Back', insights_path %>

app/views/insights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @insight.title %>
</p>

<p>
  <strong>Posted at:</strong>
  <%= @insight.posted_at %>
</p>

<p>
  <strong>Posted by:</strong>
  <%= @insight.posted_by %>
</p>

<p>
  <strong>Article text:</strong>
  <%= @insight.article_text %>
</p>

<%= link_to 'Edit', edit_insight_path(@insight) %> |
<%= link_to 'Back', insights_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LtpApi</title>
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css'%>
  <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js'%>
  <%= javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js'%>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/news_articles/_form.html.erb
<%= form_for(@news_article) do |f| %>
  <% if @news_article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news_article.errors.count, "error") %> prohibited this news_article from being saved:</h2>

      <ul>
      <% @news_article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :posted_at %><br>
    <%= f.text_field :posted_at %>
  </div>
  <div class="field">
    <%= f.label :posted_by %><br>
    <%= f.text_field :posted_by %>
  </div>
  <div class="field">
    <%= f.label :article_text %><br>
    <%= f.text_area :article_text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/news_articles/edit.html.erb
<h1>Editing News Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @news_article %> |
<%= link_to 'Back', news_articles_path %>

app/views/news_articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing News Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Posted at</th>
      <th>Posted by</th>
      <th>Article text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @news_articles.each do |news_article| %>
      <tr>
        <td><%= news_article.title %></td>
        <td><%= news_article.posted_at %></td>
        <td><%= news_article.posted_by %></td>
        <td><%= news_article.article_text %></td>
        <td><%= link_to 'Show', news_article %></td>
        <td><%= link_to 'Edit', edit_news_article_path(news_article) %></td>
        <td><%= link_to 'Destroy', news_article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New News article', new_news_article_path %>

app/views/news_articles/new.html.erb
<h1>New News Article</h1>

<%= render 'form' %>

<%= link_to 'Back', news_articles_path %>

app/views/news_articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @news_article.title %>
</p>

<p>
  <strong>Posted at:</strong>
  <%= @news_article.posted_at %>
</p>

<p>
  <strong>Posted by:</strong>
  <%= @news_article.posted_by %>
</p>

<p>
  <strong>Article text:</strong>
  <%= @news_article.article_text %>
</p>

<%= link_to 'Edit', edit_news_article_path(@news_article) %> |
<%= link_to 'Back', news_articles_path %>